// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Load the test/.env file explicitly so Prisma commands using this config
// pick up the `DATABASE_URL` defined in test/.env.
const envResult = loadEnv({
  path: new URL("./.env", import.meta.url).pathname,
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: envResult.parsed?.DATABASE_URL ?? process.env["DATABASE_URL"],
  },
});
